swagger: '2.0'
info:
  title: User Management API
  description: This API is part of the **Tourism Ecuador** platform. It handles user management functionalities, including listing, creating, updating, and deleting users in the system.
  version: "1.0.0"
  contact:
    name: Tourism Ecuador Support
    email: support@tourism-ecuador.com
    url: https://www.tourism-ecuador.com
host: localhost:7000 
basePath: /api
schemes:
  - http
paths:
  /users:
    get:
      summary: List all users
      description: Returns a list of all users stored in the **Tourism Ecuador** platform's database.
      operationId: listUsers
      produces:
        - application/json
      responses:
        200:
          description: Successfully fetched the list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        500:
          description: Internal server error

definitions:
  User:
    type: object
    required:
      - id
      - name
      - email
      - password
      - role
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "John Doe"
      email:
        type: string
        example: "john.doe@example.com"
      password:
        type: string
        example: "password123"
      role:
        type: string
        example: "user"  
