openapi: 3.0.0
info:
  title: "Tour Packages API"
  description: "Documentation of the API for querying tour packages"
  version: "1.0.0"
servers:
  - url: "http://localhost:3002/api"
paths:
  /packages:
    get:
      summary: "Get all tour packages"
      operationId: "getPackages"
      tags:
        - "Packages"
      responses:
        '200':
          description: "List of tour packages"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: "Package ID"
                    name:
                      type: string
                      description: "Package name"
                    description:
                      type: string
                      description: "Package description"
                    price:
                      type: number
                      format: float
                      description: "Package price"
                    duration:
                      type: integer
                      description: "Duration in days"
