version: '3.8'

services:
  
  auth-service:
    build:
      context: ./auth-service  
      dockerfile: Dockerfile  
    container_name: auth-service
    ports:
      - "3001:3001" 
    environment:
      - DB_HOST=users.c20pppmbajcg.us-east-1.rds.amazonaws.com 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Federer.-
      - DB_NAME=users  
      - JWT_SECRET=your_jwt_secret_key
      - ADMIN_TOKEN=supersecreto123

  
  register-service:
    build:
      context: ./register-user-service  
      dockerfile: Dockerfile       
    container_name: register-service
    ports:
      - "3000:3000"  
    environment:
      - DB_HOST=users.c20pppmbajcg.us-east-1.rds.amazonaws.com  
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Federer.-
      - DB_NAME=users  
      - JWT_SECRET=your_jwt_secret_key
