swagger: '2.0'
info:
  title: 'User Registration API'
  description: 'This API handles user registration for the Ecuador Turístico platform.'
  version: '1.0.0'
host: 'localhost:3000'
basePath: '/api'
schemes:
  - 'http'
paths:
  /register:
    post:
      summary: 'Register a new user'
      description: 'This endpoint registers a new user to the system.'
      parameters:
        - in: body
          name: body
          description: 'User information'
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
              role:
                type: string
      responses:
        200:
          description: 'User registered successfully'
        400:
          description: 'Bad Request - Missing parameters or invalid data'
        500:
          description: 'Server error'
