version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: .
    container_name: create_user_service
    restart: always
    depends_on:
      - db
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: users_db
      DB_PORT: 5432
      CORS_ORIGIN: "*"

volumes:
  pgdata:
