version: '3.8'

services:
  get-user-service:
    build: .
    container_name: get-user-service
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=users_db
      - DB_PORT=5432
      - JWT_SECRET=supersecreto
    depends_on:
      - postgres
    networks:
      - backend-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres_data:
