name: Build and Push Docker Images

on:
  push:
    branches:
      - "QA"  

    paths:
      - 'Tourism_Activities_Management/**' 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

              cd Tourism_Activities_Management
      - name: Build and Push Docker Images
        run: |
          # Construir las im치genes usando Docker Compose
          docker-compose build  # Construir las im치genes

          # Subir las im치genes a Docker Hub
          docker-compose push  # Subir las im치genes a Docker Hub
