name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar clave SSH para EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ubuntu
        run: |
          echo "$AWS_PRIVATE_KEY" > clave4.pem
          chmod 600 clave4.pem

      - name: Debug AWS Private Key
        run: |
          echo "Verificando clave privada..."
          ls -l clave4.pem

          - name: Instalar Docker en EC2 (solo si no est치 instalado)
          run: |
            ssh -i clave4.pem $AWS_USER@$AWS_HOST << 'EOF'
              if ! command -v docker &> /dev/null
              then
                echo "Docker no est치 instalado. Instalando..."
                sudo apt update
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
              else
                echo "Docker ya est치 instalado. Saltando instalaci칩n."
              fi
            EOF
        

      - name: Desplegar MongoDB y microservicios en EC2
        run: |
          ssh -i clave4.pem $AWS_USER@$AWS_HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/mongo-database:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/create-activity:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/list-activities:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/update-activity:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest

            docker stop create-activity || true
            docker stop list-activities || true
            docker stop update-activity || true
            docker stop delete-activity || true

            docker rm create-activity || true
            docker rm list-activities || true
            docker rm update-activity || true
            docker rm delete-activity || true

           
            docker run -d --name create-activity -p 4001:4001 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host --restart=always ${{ secrets.DOCKER_USERNAME }}/create-activity:latest

            docker run -d --name list-activities -p 4003:4003 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host --restart=always ${{ secrets.DOCKER_USERNAME }}/list-activities:latest

            docker run -d --name update-activity -p 4004:4004 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host --restart=always ${{ secrets.DOCKER_USERNAME }}/update-activity:latest

            docker run -d --name delete-activity -p 4005:4005 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host --restart=always ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest

          EOF
