name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Este pipeline se ejecuta después de que el CI Pipeline termine correctamente
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Usamos un runner auto-hospedado (puede ser una instancia EC2 o cualquier servidor)
    
    steps:
      # Paso 1: Descargar las imágenes Docker desde Docker Hub
      - name: Pull Docker images
        run: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mongo-database:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-activity:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/list-activities:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/update-activity:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest

      # Paso 2: Eliminar contenedores antiguos si existen
      - name: Delete old Docker containers
        run: |
          sudo docker rm -f mongodb_container || true
          sudo docker rm -f create-activity || true
          sudo docker rm -f list-activities || true
          sudo docker rm -f update-activity || true
          sudo docker rm -f delete-activity || true

      # Paso 3: Levantar MongoDB
      - name: Run MongoDB Container
        run: |
          sudo docker run -d --name mongodb_container -p 27017:27017 ${{ secrets.DOCKER_USERNAME }}/mongo-database:latest

      # Paso 4: Levantar microservicios
      - name: Run Microservices
        run: |
          sudo docker run -d --name create-activity -p 4001:4001 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host ${{ secrets.DOCKER_USERNAME }}/create-activity:latest
          sudo docker run -d --name list-activities -p 4003:4003 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host ${{ secrets.DOCKER_USERNAME }}/list-activities:latest
          sudo docker run -d --name update-activity -p 4004:4004 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host ${{ secrets.DOCKER_USERNAME }}/update-activity:latest
          sudo docker run -d --name delete-activity -p 4005:4005 --env MONGO_URI=mongodb://mongodb_container:27017/ActivitiesDB --network=host ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest
