name: CI Pipeline

on:
  push:
    branches:
      - "QA"  
    paths:
      - "Tourism_Activities_Management/**"
  pull_request:
    branches:
      - "main" 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker images
        run: |
          # No reconstruimos MongoDB, solo lo obtenemos desde Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/mongo-database:latest

          # Construcción de los microservicios usando docker build
          docker build -t ${{ secrets.DOCKER_USERNAME }}/create-activity:latest -f Tourism_Activities_Management/create-activity/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/list-activities:latest -f Tourism_Activities_Management/list-activities/Dockerfile . 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/update-activity:latest -f Tourism_Activities_Management/update-activity/Dockerfile . 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest -f Tourism_Activities_Management/delete-activity/Dockerfile . 

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/create-activity:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/list-activities:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/update-activity:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/delete-activity:latest
