name: CI Pipeline

on:
  push:
    branches:
      - "QA"
    paths:
      - "Tourism_Activities_Management/**"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [create-activity, list-activities, update-activity, delete-activity]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull MongoDB image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mongo-database:latest

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c 1-7)
          docker buildx build --platform linux/amd64,linux/arm64 --push --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${IMAGE_TAG} -f Tourism_Activities_Management/${{ matrix.service }}/Dockerfile .