name: CI/CD Route Management

on:
  push:
    branches:
      - QA
    paths:
      - 'Route-Management/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables from GitHub secrets
        run: |
          echo "DB_HOST_US=${{ secrets.DB_HOST_US }}" >> $GITHUB_ENV
          echo "DB_PORT_US=${{ secrets.DB_PORT_US }}" >> $GITHUB_ENV
          echo "DB_USER_US=${{ secrets.DB_USER_US }}" >> $GITHUB_ENV
          echo "DB_PASSWORD_US=${{ secrets.DB_PASSWORD_US }}" >> $GITHUB_ENV
          echo "DB_NAME_RO=${{ secrets.DB_NAME_RO }}" >> $GITHUB_ENV

      - name: Instalar Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y Subir Imágenes Docker con Docker Compose
        working-directory: Route-Management
        run: |
          # Construir las imágenes usando Docker Compose
          sudo docker-compose build --no-cache

          # Subir las imágenes a Docker Hub usando Docker Compose
          # sudo docker-compose push

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo de clave privada
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > clave4.pem
          chmod 600 clave4.pem

      - name: Verificar conexión SSH antes de ejecutar comandos
        run: |
          echo "Probando conexión a ${{ secrets.AWS_HOST_RO }}"
          ping -c 3 ${{ secrets.AWS_HOST_RO }} || echo "No responde al ping"
          ssh -o StrictHostKeyChecking=no -i clave4.pem ec2-user@${{ secrets.AWS_HOST_RO }} "echo 'Conexión SSH exitosa'"
        continue-on-error: true

      - name: Exportar variables de entorno para Docker
        run: |
          echo "DB_HOST_US=${{ secrets.DB_HOST_US }}" >> $GITHUB_ENV
          echo "DB_PORT_US=${{ secrets.DB_PORT_US }}" >> $GITHUB_ENV
          echo "DB_USER_US=${{ secrets.DB_USER_US }}" >> $GITHUB_ENV
          echo "DB_PASSWORD_US=${{ secrets.DB_PASSWORD_US }}" >> $GITHUB_ENV
          echo "DB_NAME_US=${{ secrets.DB_NAME_RO }}" >> $GITHUB_ENV

      - name: SSH into EC2 and run Docker commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST_RO }}
          username: ec2-user
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            echo "Iniciando sesión en EC2..."
            cd /home/ec2-user

            sudo docker stop create-route get-routes update-route delete-route || true
            sudo docker rm create-route get-routes update-route delete-route || true

            sudo docker pull xaviercuases/create-route:latest
            sudo docker pull xaviercuases/get-routes:latest
            sudo docker pull xaviercuases/update-route:latest
            sudo docker pull xaviercuases/delete-route:latest

            sudo docker run -d --restart always --name create-route -p 5005:5005 xaviercuases/create-route:latest
            sudo docker run -d --restart always --name get-routes -p 5006:5006 xaviercuases/get-routes:latest
            sudo docker run -d --restart always --name update-route -p 5007:5007 xaviercuases/update-route:latest
            sudo docker run -d --restart always --name delete-route -p 5008:5008 xaviercuases/delete-route:latest
