name: CI/CD Route Management

on:
  push:
    branches:
      - QA
    paths:
      - 'Route-Management/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables from GitHub secrets
        run: |
          echo "DB_HOST_US=${{ secrets.DB_HOST_US }}" >> $GITHUB_ENV
          echo "DB_PORT_US=${{ secrets.DB_PORT_US }}" >> $GITHUB_ENV
          echo "DB_USER_US=${{ secrets.DB_USER_US }}" >> $GITHUB_ENV
          echo "DB_PASSWORD_US=${{ secrets.DB_PASSWORD_US }}" >> $GITHUB_ENV
          echo "DB_NAME_RO=${{ secrets.DB_NAME_RO }}" >> $GITHUB_ENV

      - name: Instalar Docker CE y eliminar contenedores antiguos
        run: |
          sudo apt-get update
          sudo apt-get remove --purge docker.io containerd runc -y
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      # Paso para verificar el login manual en Docker Hub
      - name: Test Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Construir y Subir Imágenes Docker
        working-directory: Route-Management
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/create-route:latest ./create-route
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/get-routes:latest ./get-routes
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/update-route:latest ./update-route
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/delete-route:latest ./delete-route

          #sudo docker push ${{ secrets.DOCKER_USERNAME }}/create-route:latest
          #sudo docker push ${{ secrets.DOCKER_USERNAME }}/get-routes:latest
          #sudo docker push ${{ secrets.DOCKER_USERNAME }}/update-route:latest
          #sudo docker push ${{ secrets.DOCKER_USERNAME }}/delete-route:latest
